name: riverpod_demo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1
  riverpod_annotation: ^2.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  build_runner:

flutter:

  uses-material-design: true
