name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jacopocarlini/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_prefix: "v"