name: Create Tag

on:
  push:
    branches:
      - master
env:
  flutter_version: '3.10.4'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.flutter_version }}
            channel: 'stable'
            cache: true
            - run: flutter pub get
      - uses: jacopocarlini/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_prefix: "v"